/*
-- Volcado de datos para la tabla provincias
*/

INSERT INTO provincias (idprovincia, provincia) VALUES
(15, 'A Coruña'),
(1, 'Alava'),
(2, 'Albacete'),
(3, 'Alicante'),
(4, 'Almeria'),
(33, 'Asturias'),
(5, 'Ávila'),
(6, 'badajoz'),
(7, 'baleares'),
(8, 'barcelona'),
(9, 'burgos'),
(10, 'caceres'),
(11, 'cadiz'),
(39, 'cantabria'),
(12, 'castellon'),
(51, 'ceuta'),
(13, 'ciudad real'),
(14, 'cordoba'),
(16, 'cuenca'),
(17, 'gerona'),
(18, 'granada'),
(19, 'guadalajara'),
(20, 'guipuzcoa'),
(21, 'huelva'),
(22, 'huesca'),
(23, 'jaen'),
(26, 'la rioja'),
(35, 'las palmas'),
(24, 'leon'),
(25, 'lerida'),
(27, 'lugo'),
(28, 'madrid'),
(29, 'malaga'),
(52, 'melilla'),
(30, 'murcia'),
(31, 'navarra'),
(32, 'orense'),
(34, 'palencia'),
(36, 'pontevedra'),
(37, 'salamanca'),
(38, 'santa cruz de tenerife'),
(40, 'segovia'),
(41, 'sevilla'),
(42, 'soria'),
(43, 'tarragona'),
(44, 'teruel'),
(45, 'toledo'),
(46, 'Valencia'),
(47, 'valladolid'),
(48, 'vizcaya'),
(49, 'zamora'),
(50, 'zaragoza');
