INSERT INTO paises (idpais, nom_pais) VALUES (1, 'Afganistán');
INSERT INTO paises (idpais, nom_pais) VALUES (2, 'Albania');
INSERT INTO paises (idpais, nom_pais) VALUES (3, 'Alemania');
INSERT INTO paises (idpais, nom_pais) VALUES (4, 'Andorra');
INSERT INTO paises (idpais, nom_pais) VALUES (5, 'Angola');
INSERT INTO paises (idpais, nom_pais) VALUES (6, 'Anguila');
INSERT INTO paises (idpais, nom_pais) VALUES (7, 'Antigua y Barbuda');
INSERT INTO paises (idpais, nom_pais) VALUES (8, 'Antártida');
INSERT INTO paises (idpais, nom_pais) VALUES (9, 'Arabia Saudita');
INSERT INTO paises (idpais, nom_pais) VALUES (10,'Argelia');
INSERT INTO paises (idpais, nom_pais) VALUES (11,'Argentina');
INSERT INTO paises (idpais, nom_pais) VALUES (12,'Armenia');
INSERT INTO paises (idpais, nom_pais) VALUES (13,'Aruba');
INSERT INTO paises (idpais, nom_pais) VALUES (14,'Australia');
INSERT INTO paises (idpais, nom_pais) VALUES (15,'Austria');
INSERT INTO paises (idpais, nom_pais) VALUES (16,'Azerbaiyán');
INSERT INTO paises (idpais, nom_pais) VALUES (17,'Bahamas (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (18, 'Bangladés');
INSERT INTO paises (idpais, nom_pais) VALUES (19, 'Barbados');
INSERT INTO paises (idpais, nom_pais) VALUES (20, 'Baréin');
INSERT INTO paises (idpais, nom_pais) VALUES (21, 'Belice');
INSERT INTO paises (idpais, nom_pais) VALUES (22, 'Benín');
INSERT INTO paises (idpais, nom_pais) VALUES (23, 'Bermudas');
INSERT INTO paises (idpais, nom_pais) VALUES (24, 'Bielorrusia');
INSERT INTO paises (idpais, nom_pais) VALUES (25, 'Bolivia');
INSERT INTO paises (idpais, nom_pais) VALUES (26, 'Bonaire San Eustaquio y Saba');
INSERT INTO paises (idpais, nom_pais) VALUES (27, 'Bosnia y Herzegovina');
INSERT INTO paises (idpais, nom_pais) VALUES (28, 'Botsuana');
INSERT INTO paises (idpais, nom_pais) VALUES (29, 'Brasil');
INSERT INTO paises (idpais, nom_pais) VALUES (30, 'Brunéi Darussalam');
INSERT INTO paises (idpais, nom_pais) VALUES (31, 'Bulgaria');
INSERT INTO paises (idpais, nom_pais) VALUES (32, 'Burkina Faso');
INSERT INTO paises (idpais, nom_pais) VALUES (33, 'Burundi');
INSERT INTO paises (idpais, nom_pais) VALUES (34, 'Bután');
INSERT INTO paises (idpais, nom_pais) VALUES (35, 'Bélgica');
INSERT INTO paises (idpais, nom_pais) VALUES (36, 'Cabo Verde');
INSERT INTO paises (idpais, nom_pais) VALUES (37, 'Camboya');
INSERT INTO paises (idpais, nom_pais) VALUES (38, 'Camerún');
INSERT INTO paises (idpais, nom_pais) VALUES (39, 'Canadá');
INSERT INTO paises (idpais, nom_pais) VALUES (40, 'Catar');
INSERT INTO paises (idpais, nom_pais) VALUES (41, 'Chad');
INSERT INTO paises (idpais, nom_pais) VALUES (42, 'Chile');
INSERT INTO paises (idpais, nom_pais) VALUES (43, 'China');
INSERT INTO paises (idpais, nom_pais) VALUES (44, 'Chipre');
INSERT INTO paises (idpais, nom_pais) VALUES (45, 'Colombia');
INSERT INTO paises (idpais, nom_pais) VALUES (46, 'Comoras');
INSERT INTO paises (idpais, nom_pais) VALUES (47, 'Congo');
INSERT INTO paises (idpais, nom_pais) VALUES (48, 'Congo (la República Democrática del)');
INSERT INTO paises (idpais, nom_pais) VALUES (49, 'Corea (la República Democrática Popular de)');
INSERT INTO paises (idpais, nom_pais) VALUES (50, 'Corea (la República de)');
INSERT INTO paises (idpais, nom_pais) VALUES (51, 'Costa Rica');
INSERT INTO paises (idpais, nom_pais) VALUES (52, 'Cote d Ivoire');
INSERT INTO paises (idpais, nom_pais) VALUES (53, 'Croacia');
INSERT INTO paises (idpais, nom_pais) VALUES (54, 'Cuba');
INSERT INTO paises (idpais, nom_pais) VALUES (55, 'Curaçao');
INSERT INTO paises (idpais, nom_pais) VALUES (56, 'Dinamarca');
INSERT INTO paises (idpais, nom_pais) VALUES (57, 'Dominica');
INSERT INTO paises (idpais, nom_pais) VALUES (58, 'Ecuador');
INSERT INTO paises (idpais, nom_pais) VALUES (59, 'Egipto');
INSERT INTO paises (idpais, nom_pais) VALUES (60, 'El Salvador');
INSERT INTO paises (idpais, nom_pais) VALUES (61, 'Emiratos Árabes Unidos (Los)');
INSERT INTO paises (idpais, nom_pais) VALUES (62, 'Eritrea');
INSERT INTO paises (idpais, nom_pais) VALUES (63, 'Eslovaquia');
INSERT INTO paises (idpais, nom_pais) VALUES (64, 'Eslovenia');
INSERT INTO paises (idpais, nom_pais) VALUES (65, 'España');
INSERT INTO paises (idpais, nom_pais) VALUES (66, 'Estados Unidos (los)');
INSERT INTO paises (idpais, nom_pais) VALUES (67, 'Estonia');
INSERT INTO paises (idpais, nom_pais) VALUES (68, 'Etiopía');
INSERT INTO paises (idpais, nom_pais) VALUES (69, 'Filipinas (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (70, 'Finlandia');
INSERT INTO paises (idpais, nom_pais) VALUES (71, 'Fiyi');
INSERT INTO paises (idpais, nom_pais) VALUES (72, 'Francia');
INSERT INTO paises (idpais, nom_pais) VALUES (73, 'Gabón');
INSERT INTO paises (idpais, nom_pais) VALUES (74, 'Gambia (La)');
INSERT INTO paises (idpais, nom_pais) VALUES (75, 'Georgia');
INSERT INTO paises (idpais, nom_pais) VALUES (76, 'Georgia del sur y las islas sandwich del sur');
INSERT INTO paises (idpais, nom_pais) VALUES (77, 'Ghana');
INSERT INTO paises (idpais, nom_pais) VALUES (78, 'Gibraltar');
INSERT INTO paises (idpais, nom_pais) VALUES (79, 'Granada');
INSERT INTO paises (idpais, nom_pais) VALUES (80, 'Grecia');
INSERT INTO paises (idpais, nom_pais) VALUES (81, 'Groenlandia');
INSERT INTO paises (idpais, nom_pais) VALUES (82, 'Guadalupe');
INSERT INTO paises (idpais, nom_pais) VALUES (83, 'Guam');
INSERT INTO paises (idpais, nom_pais) VALUES (84, 'Guatemala');
INSERT INTO paises (idpais, nom_pais) VALUES (85, 'Guayana Francesa');
INSERT INTO paises (idpais, nom_pais) VALUES (86, 'Guernsey');
INSERT INTO paises (idpais, nom_pais) VALUES (87, 'Guinea');
INSERT INTO paises (idpais, nom_pais) VALUES (88, 'Guinea Ecuatorial');
INSERT INTO paises (idpais, nom_pais) VALUES (89, 'Guinea-Bisáu');
INSERT INTO paises (idpais, nom_pais) VALUES (90, 'Guyana');
INSERT INTO paises (idpais, nom_pais) VALUES (91, 'Haití');
INSERT INTO paises (idpais, nom_pais) VALUES (92, 'Honduras');
INSERT INTO paises (idpais, nom_pais) VALUES (93, 'Hong Kong');
INSERT INTO paises (idpais, nom_pais) VALUES (94, 'Hungría');
INSERT INTO paises (idpais, nom_pais) VALUES (95, 'India');
INSERT INTO paises (idpais, nom_pais) VALUES (96, 'Indonesia');
INSERT INTO paises (idpais, nom_pais) VALUES (97, 'Irak');
INSERT INTO paises (idpais, nom_pais) VALUES (98, 'Irlanda');
INSERT INTO paises (idpais, nom_pais) VALUES (99, 'Irán (la República Islámica de)');
INSERT INTO paises (idpais, nom_pais) VALUES (100, 'Isla Bouvet');
INSERT INTO paises (idpais, nom_pais) VALUES (101, 'Isla Heard e Islas McDonald');
INSERT INTO paises (idpais, nom_pais) VALUES (102, 'Isla Norfolk');
INSERT INTO paises (idpais, nom_pais) VALUES (103, 'Isla de Man');
INSERT INTO paises (idpais, nom_pais) VALUES (104, 'Isla de Navidad');
INSERT INTO paises (idpais, nom_pais) VALUES (105, 'Islandia');
INSERT INTO paises (idpais, nom_pais) VALUES (106, 'Islas Caimán (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (107, 'Islas Cocos (Keeling)');
INSERT INTO paises (idpais, nom_pais) VALUES (108, 'Islas Cook (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (109, 'Islas Feroe (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (110, 'Islas Malvinas [Falkland] (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (111, 'Islas Marianas del Norte (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (112, 'Islas Marshall (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (113, 'Islas Salomón (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (114, 'Islas Turcas y Caicos (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (115, 'Islas Vírgenes (Británicas)');
INSERT INTO paises (idpais, nom_pais) VALUES (116, 'Islas Vírgenes (EE.UU.)');
INSERT INTO paises (idpais, nom_pais) VALUES (117, 'Islas de Ultramar Menores de Estados Unidos (las)');
INSERT INTO paises (idpais, nom_pais) VALUES (118, 'Islas Åland');
INSERT INTO paises (idpais, nom_pais) VALUES (119, 'Israel');
INSERT INTO paises (idpais, nom_pais) VALUES (120, 'Italia');
INSERT INTO paises (idpais, nom_pais) VALUES (121, 'Jamaica');
INSERT INTO paises (idpais, nom_pais) VALUES (122, 'Japón');
INSERT INTO paises (idpais, nom_pais) VALUES (123, 'Jersey');
INSERT INTO paises (idpais, nom_pais) VALUES (124, 'Jordania');
INSERT INTO paises (idpais, nom_pais) VALUES (125, 'Kazajistán');
INSERT INTO paises (idpais, nom_pais) VALUES (126, 'Kenia');
INSERT INTO paises (idpais, nom_pais) VALUES (127, 'Kirguistán');
INSERT INTO paises (idpais, nom_pais) VALUES (128, 'Kiribati');
INSERT INTO paises (idpais, nom_pais) VALUES (129, 'Kuwait');
INSERT INTO paises (idpais, nom_pais) VALUES (130, 'Lao, (la) República Democrática Popular');
INSERT INTO paises (idpais, nom_pais) VALUES (131, 'Lesoto');
INSERT INTO paises (idpais, nom_pais) VALUES (132, 'Letonia');
INSERT INTO paises (idpais, nom_pais) VALUES (133, 'Liberia');
INSERT INTO paises (idpais, nom_pais) VALUES (134, 'Libia');
INSERT INTO paises (idpais, nom_pais) VALUES (135, 'Liechtenstein');
INSERT INTO paises (idpais, nom_pais) VALUES (136, 'Lituania');
INSERT INTO paises (idpais, nom_pais) VALUES (137, 'Luxemburgo');
INSERT INTO paises (idpais, nom_pais) VALUES (138, 'Líbano');
INSERT INTO paises (idpais, nom_pais) VALUES (139, 'Macao');
INSERT INTO paises (idpais, nom_pais) VALUES (140, 'Macedonia (la antigua República Yugoslava de)');
INSERT INTO paises (idpais, nom_pais) VALUES (141, 'Madagascar');
INSERT INTO paises (idpais, nom_pais) VALUES (142, 'Malasia');
INSERT INTO paises (idpais, nom_pais) VALUES (143, 'Malaui');
INSERT INTO paises (idpais, nom_pais) VALUES (144, 'Maldivas');
INSERT INTO paises (idpais, nom_pais) VALUES (145, 'Malta');
INSERT INTO paises (idpais, nom_pais) VALUES (146, 'Malí');
INSERT INTO paises (idpais, nom_pais) VALUES (147, 'Marruecos');
INSERT INTO paises (idpais, nom_pais) VALUES (148, 'Martinica');
INSERT INTO paises (idpais, nom_pais) VALUES (149, 'Mauricio');
INSERT INTO paises (idpais, nom_pais) VALUES (150, 'Mauritania');
INSERT INTO paises (idpais, nom_pais) VALUES (151, 'Mayotte');
INSERT INTO paises (idpais, nom_pais) VALUES (152, 'Micronesia (los Estados Federados de)');
INSERT INTO paises (idpais, nom_pais) VALUES (153, 'Moldavia (la República de)');
INSERT INTO paises (idpais, nom_pais) VALUES (154, 'Mongolia');
INSERT INTO paises (idpais, nom_pais) VALUES (155, 'Montenegro');
INSERT INTO paises (idpais, nom_pais) VALUES (156, 'Montserrat');
INSERT INTO paises (idpais, nom_pais) VALUES (157, 'Mozambique');
INSERT INTO paises (idpais, nom_pais) VALUES (158, 'Myanmar');
INSERT INTO paises (idpais, nom_pais) VALUES (159, 'México');
INSERT INTO paises (idpais, nom_pais) VALUES (160, 'Mónaco');
INSERT INTO paises (idpais, nom_pais) VALUES (161, 'Namibia');
INSERT INTO paises (idpais, nom_pais) VALUES (162, 'Nauru');
INSERT INTO paises (idpais, nom_pais) VALUES (163, 'Nepal');
INSERT INTO paises (idpais, nom_pais) VALUES (164, 'Nicaragua');
INSERT INTO paises (idpais, nom_pais) VALUES (165, 'Nigeria');
INSERT INTO paises (idpais, nom_pais) VALUES (166, 'Niue');
INSERT INTO paises (idpais, nom_pais) VALUES (167, 'Noruega');
INSERT INTO paises (idpais, nom_pais) VALUES (168, 'Nueva Caledonia');
INSERT INTO paises (idpais, nom_pais) VALUES (169, 'Nueva Zelanda');
INSERT INTO paises (idpais, nom_pais) VALUES (170, 'Níger (el)');
INSERT INTO paises (idpais, nom_pais) VALUES (171, 'Omán');
INSERT INTO paises (idpais, nom_pais) VALUES (172, 'Pakistán');
INSERT INTO paises (idpais, nom_pais) VALUES (173, 'Palaos');
INSERT INTO paises (idpais, nom_pais) VALUES (174, 'Palestina');
INSERT INTO paises (idpais, nom_pais) VALUES (175, 'Panamá');
INSERT INTO paises (idpais, nom_pais) VALUES (176, 'Papúa Nueva Guinea');
INSERT INTO paises (idpais, nom_pais) VALUES (177, 'Paraguay');
INSERT INTO paises (idpais, nom_pais) VALUES (178, 'Países Bajos (los)');
INSERT INTO paises (idpais, nom_pais) VALUES (179, 'Perú');
INSERT INTO paises (idpais, nom_pais) VALUES (180, 'Pitcairn');
INSERT INTO paises (idpais, nom_pais) VALUES (181, 'Polinesia Francesa');
INSERT INTO paises (idpais, nom_pais) VALUES (182, 'Polonia');
INSERT INTO paises (idpais, nom_pais) VALUES (183, 'Portugal');
INSERT INTO paises (idpais, nom_pais) VALUES (184, 'Puerto Rico');
INSERT INTO paises (idpais, nom_pais) VALUES (185, 'Reino Unido (el)');
INSERT INTO paises (idpais, nom_pais) VALUES (186, 'República Centroafricana (la)');
INSERT INTO paises (idpais, nom_pais) VALUES (187, 'República Checa (la)');
INSERT INTO paises (idpais, nom_pais) VALUES (188, 'República Dominicana (la)');
INSERT INTO paises (idpais, nom_pais) VALUES (189, 'Reunión');
INSERT INTO paises (idpais, nom_pais) VALUES (190, 'Ruanda');
INSERT INTO paises (idpais, nom_pais) VALUES (191, 'Rumania');
INSERT INTO paises (idpais, nom_pais) VALUES (192, 'Rusia');
INSERT INTO paises (idpais, nom_pais) VALUES (193, 'Sahara Occidental');
INSERT INTO paises (idpais, nom_pais) VALUES (194, 'Samoa');
INSERT INTO paises (idpais, nom_pais) VALUES (195, 'Samoa Americana');
INSERT INTO paises (idpais, nom_pais) VALUES (196, 'San Bartolomé');
INSERT INTO paises (idpais, nom_pais) VALUES (197, 'San Cristóbal y Nieves');
INSERT INTO paises (idpais, nom_pais) VALUES (198, 'San Marino');
INSERT INTO paises (idpais, nom_pais) VALUES (199, 'San Martín (parte francesa)');
INSERT INTO paises (idpais, nom_pais) VALUES (200, 'San Pedro y Miquelón');
INSERT INTO paises (idpais, nom_pais) VALUES (201, 'San Vicente y las Granadinas');
INSERT INTO paises (idpais, nom_pais) VALUES (202, 'Santa Helena');
INSERT INTO paises (idpais, nom_pais) VALUES (203, 'Santa Lucía');
INSERT INTO paises (idpais, nom_pais) VALUES (204, 'Estado de la Ciudad del Vaticano');
INSERT INTO paises (idpais, nom_pais) VALUES (205, 'Santo Tomé y Príncipe');
INSERT INTO paises (idpais, nom_pais) VALUES (206, 'Senegal');
INSERT INTO paises (idpais, nom_pais) VALUES (207, 'Serbia');
INSERT INTO paises (idpais, nom_pais) VALUES (208, 'Seychelles');
INSERT INTO paises (idpais, nom_pais) VALUES (209, 'Sierra Leona');
INSERT INTO paises (idpais, nom_pais) VALUES (210, 'Singapur');
INSERT INTO paises (idpais, nom_pais) VALUES (211, 'Sint Maarten (parte holandesa)');
INSERT INTO paises (idpais, nom_pais) VALUES (212, 'Siria(la) República Árabe');
INSERT INTO paises (idpais, nom_pais) VALUES (213, 'Somalia');
INSERT INTO paises (idpais, nom_pais) VALUES (214, 'Sri Lanka');
INSERT INTO paises (idpais, nom_pais) VALUES (215, 'Suazilandia');
INSERT INTO paises (idpais, nom_pais) VALUES (216, 'Sudáfrica');
INSERT INTO paises (idpais, nom_pais) VALUES (217, 'Sudán (el)');
INSERT INTO paises (idpais, nom_pais) VALUES (218, 'Sudán del Sur');
INSERT INTO paises (idpais, nom_pais) VALUES (219, 'Suecia');
INSERT INTO paises (idpais, nom_pais) VALUES (220, 'Suiza');
INSERT INTO paises (idpais, nom_pais) VALUES (221, 'Surinam');
INSERT INTO paises (idpais, nom_pais) VALUES (222, 'Svalbard y Jan Mayen');
INSERT INTO paises (idpais, nom_pais) VALUES (223, 'Tailandia');
INSERT INTO paises (idpais, nom_pais) VALUES (224, 'Taiwán (Provincia de China)');
INSERT INTO paises (idpais, nom_pais) VALUES (225, 'Tanzania, República Unida de');
INSERT INTO paises (idpais, nom_pais) VALUES (226, 'Tayikistán');
INSERT INTO paises (idpais, nom_pais) VALUES (227, 'Territorio Británico del Océano Índico (el)');
INSERT INTO paises (idpais, nom_pais) VALUES (228, 'Territorios Australes Franceses (los)');
INSERT INTO paises (idpais, nom_pais) VALUES (229, 'Timor-Leste');
INSERT INTO paises (idpais, nom_pais) VALUES (230, 'Togo');
INSERT INTO paises (idpais, nom_pais) VALUES (231, 'Tokelau');
INSERT INTO paises (idpais, nom_pais) VALUES (232, 'Tonga');
INSERT INTO paises (idpais, nom_pais) VALUES (233, 'Trinidad y Tobago');
INSERT INTO paises (idpais, nom_pais) VALUES (234, 'Turkmenistán');
INSERT INTO paises (idpais, nom_pais) VALUES (235, 'Turquía');
INSERT INTO paises (idpais, nom_pais) VALUES (236, 'Tuvalu');
INSERT INTO paises (idpais, nom_pais) VALUES (237, 'Túnez');
INSERT INTO paises (idpais, nom_pais) VALUES (238, 'Ucrania');
INSERT INTO paises (idpais, nom_pais) VALUES (239, 'Uganda');
INSERT INTO paises (idpais, nom_pais) VALUES (240, 'Uruguay');
INSERT INTO paises (idpais, nom_pais) VALUES (241, 'Uzbekistán');
INSERT INTO paises (idpais, nom_pais) VALUES (242, 'Vanuatu');
INSERT INTO paises (idpais, nom_pais) VALUES (243, 'Venezuela');
INSERT INTO paises (idpais, nom_pais) VALUES (244, 'Viet Nam');
INSERT INTO paises (idpais, nom_pais) VALUES (245, 'Wallis y Futuna');
INSERT INTO paises (idpais, nom_pais) VALUES (246, 'Yemen');
INSERT INTO paises (idpais, nom_pais) VALUES (247, 'Yibuti');
INSERT INTO paises (idpais, nom_pais) VALUES (248, 'Zambia');
INSERT INTO paises (idpais, nom_pais) VALUES (249, 'Zimbabue');
